### ISSUE TITLE
ODBC drivers not installing on Mojave / homebrew install

### ISSUE THREAD

**Issue by edodge** [mdbtools/mdbtools#146]
I installed mdbtools via homebrew and didn't get any error messages or warnings so the install seemed to be successful. However, I don't see the related mdb ODBC driver in my /usr/local/lib directory. I also ran a -find- command for libmdbodbc and it looks like it isn't elsewhere on my system. Any idea why the ODBC driver didn't install with the rest of the package?

I'm on Mojave 10.14.2 and I already have unixodbc 2.3.7 installed.

**Comment by alspringsteen** [comment]
I also brew installed unixodbc and mdbtools and had this issue. The flag to install mdbtools with unixodbc is not in the homebrew formula by default. I had to follow the instructions here to install using the makefile, etc. for the libraries to install. 

I have not done what I outline below myself (except to verify it will install), since I don't want to mess with what I have working already, but I think the way to get this to work is:

a) uninstall mdbtools   
`brew uninstall mdbtools`
b) edit the local version of the formula 
`brew edit mdtools` 
You need to change what is currently line 26 from:     
         `system "./configure", "--prefix=#{prefix}", "--disable-man" `   
to:      
         `system "./configure", "--prefix=#{prefix}", ""--with-unixodbc=/usr/local", "--disable-man"`
c) then install mdbtools   
  `brew install mdbtools`

Again, I can't verify this works, but I think that's what is missing from the formula. Since unixodbc appears to be an optional flag and not a dependency, and iodbc could be used instead, the flag is not included by default.

**Comment by evanmiller** [comment]
This is an issue for the Homebrew maintainer.
