### ISSUE TITLE
The New Future of mdbtools

### ISSUE THREAD

**Issue by pedromorgan** [mdbtools/mdbtools#167]
So straight up a few changes have happened in recent covid.19 time.space...
and hopefully the snag is that we all resolve in limbo with unmaintained code..

so with a new kinda freedom in that @brianb has moved project, 
it means all us mad.nutters down here in the jet engine room can tune to our advantage.. and for the future into 2050 ;-))))

## 1 new org at gh/mdbtools

I created the org and added @evanmiller and  @brianb the BDFL..

- we dont want the same snag as before where only an individual in charge, who gets run over by a bus
- we need more contribs and control and some person responsible
- imho anyone who puts in a PR that works, should have some control

The idea is to create a 'next' branch where all stuff goes in, and when it works and passed tests, int's into master

Main thing is that we need some of u dev's out there to have some control of the org.. so its not locked up like before..

## critical code

- is seems that @evanmiller has got a grip on things but thereagain a problem of code committed to master and crash
- so can i suggest we add a few coders to the "org" 

and move on from there

**Comment by evanmiller** [comment]
Thank you @pedromorgan for getting the ball rolling! I was able to get brianb's repo transferred here and also have admin access on the Sourceforge site so we can start transferring assets.

Here's what I have done so far:

* Rolled all the patches and pull requests I could find into #162 for comment
* Transferred tar balls and releases on Sourceforge into GitHub releases (also tagged relevant commits)
* Cleaned up the issue tracker, with 70 open tickets down to 17 and 20 open PRs down to 4
* Created a `dev` branch where we can deploy proposed changes before merging to master

I agree that master should NOT break and ideally should always represent the latest stable release. So automated testing will be important.

Here's what I am working on now:

* Setting up Travis and Appveyor to work with the new repo
* Setting up fuzz-testing over at google/oss-fuzz
* Reviewing the remaining open pull requests

My goal here is to whip the code into shape in order to get rid of bugs and provide a new stable point release that distros can deploy. I would like to see others involved (if there are willing volunteers) and I agree that going forward we need to avoid dependence on a single developer.

**Comment by pedromorgan** [comment]
most of this is done so closing..
