### ISSUE TITLE
SQL where clause case sensitivity

### ISSUE THREAD

**Issue by apacifici** [mdbtools/mdbtools#233]
Is there a way to have a  case insensitive where clause on mdb-sql ?
In old mdb file, using `select * from table where column like '%dummy%'` and `select * from table where column like '%Dummy%`' gives the same result on Access but only the second give result on mdb-sql.

**Comment by evanmiller** [comment]
I believe the case sensitivity can be turned off by changing the following `strncmp` to `strncasecmp`:

https://github.com/mdbtools/mdbtools/blob/9e883cb100bc68f9c469f1d88fe06a2f7fc85597/src/libmdb/like.c#L64

Someone who knows more about SQL than me might want to weigh in on the correct case sensitivity behavior here.

**Comment by evanmiller** [comment]
This page:

https://support.microsoft.com/en-us/office/like-operator-b2f7ef03-9085-4ffb-9829-eef18358e931

Indicates that Access's LIKE is case insensitive. I guess the broader question is whether MDB Tools should imitate Access or not in this respect. As far as syntax goes, our SQL dialect is mostly ANSI with percent signs and underscores for wildcards (Access uses asterisks and question marks).

**Comment by apacifici** [comment]
In my opinion an option should trigger case sensitivity on and off. This option should be a commandline option in `mdb-sql` and a connection string option in the `odbc` driver.

**Comment by evanmiller** [comment]
Well, after some more research, I am realizing how difficult this will be to implement across platforms and locales. An ASCII version will be easy, but as soon as you start thinking about diacritics (ü vs Ü) it gets messy.

It looks like strcasecmp on Apple platforms is locale-aware. I assume that means collation happens in the current locale (LC_COLLATE), but it may also mean that strings are assumed to be encoded in the current locale. This could present a problem for non-UTF-8 locales since we use a lot of UTF-8 internally.

POSIX states that if the LC_CTYPE is not POSIX/C, the results of strcasecmp are undefined. So we might not get very far with that function on Linux / Windows, since the C locale does not support UTF-8.

So while a quick and dirty version that works for `dummy` and `Dummy` would be relatively, a complete solution might be a tough nut to crack without bringing in a Unicode library.

**Comment by evanmiller** [comment]
Some additional notes:

It looks like the GLib functions [`g_utf8_casefold`](https://developer.gnome.org/glib/stable/glib-Unicode-Manipulation.html#g-utf8-casefold) and g_utf8_collate can be used to perform locale-aware, case-insensitive comparisons on UTF-8 data. So we could likely use that for people who compile libmdb with GLib installed.

We would still need an alternative for those who compile without GLib - maybe an ASCII only solution would be acceptable, perhaps with a configure-time warning.

**Comment by evanmiller** [comment]
Hi, I am working on a solution over at #244 if you'd like to test it out.
