### ISSUE TITLE
Remove scientific notation for numeric fields

### ISSUE THREAD

**Issue by kodonnell** [mdbtools/mdbtools#84]
While using mdb-export, it seems that the numeric fields (e.g. latitude/longitude) are being exported in scientific notation e.g. '1.2345678e+01'. Is there a way around this?

I'm on centOS 7, using MDBTools 0.7.1. 

[I note that someone else has reported this [here](http://sourceforge.net/p/mdbtools/bugs/133/).]

**Comment by marks** [comment]
+1 

@ianhoolihan - did you find a solution?

**Comment by ianhoolihan** [comment]
Afraid not @marks. That said, it turned out to be unnecessary -- our version of MySQL natively handled casting scientific notation as decimal. If that doesn't work for you, there do appear to be ways to do it using awk, etc.

If I knew anything about the programming language used, I'd try to figure it out ... though I'm hoping a dev will shed some light first.

**Comment by edi-bice** [comment]
+1

same here with latest version built from source

**Comment by corpx** [comment]
+1

**Comment by thezelja** [comment]
+1

**Comment by dhavalpzala** [comment]
+1

**Comment by evanmiller** [comment]
Hi all, this issue is addressed in https://github.com/mdbtools/mdbtools/commit/76c2ada332e34a79e6bc02b256820e2a43a08581 and will be a part of a future release.

Scientific notation will still be used for very small and very large numbers, but regular notation will be used in most cases.

**Comment by evanmiller** [comment]
Fixed in 0.9.1
